### ISSUE TITLE
moodledocker-exec does not work at all if any(!) project uses a static moodle source

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodledocker#5]
If any project uses a static moodle source - instead of a symlink to some repository located elsewhere - moodledocker-exec will fail since `File.readlink` cannot be applied to a non-link. 

```
home/j_dage01/Docker/Metafiles/Scripts/moodledocker-common.rb:62:in `readlink': Invalid argument @ rb_readlink - /home/j_dage01/Docker/production3_0/moodle (Errno::EINVAL)
        from /home/j_dage01/Docker/Metafiles/Scripts/moodledocker-common.rb:62:in `block in project_name'
        from /home/j_dage01/Docker/Metafiles/Scripts/moodledocker-common.rb:62:in `select'
        from /home/j_dage01/Docker/Metafiles/Scripts/moodledocker-common.rb:62:in `project_name'
        from /home/j_dage01/Docker/Metafiles/Scripts/moodledocker-exec:9:in `execute_on_docker'
        from /home/j_dage01/Docker/Metafiles/Scripts/moodledocker-exec:33:in `<main>'
```

a0a99e8b1a50ded86c6220b65f7261bfbdd08296 fixes this for `project_path`, but `project_name` is more complex so that the fix cannot be applied identically.

**Comment by dashohoxha** [comment]
I don't have any actual suggestion for fixing this problem, but have a look at my approach and maybe you will get some inspiration:
 - https://github.com/docker-scripts/moodle
 - https://github.com/docker-scripts/ds
